---
include:
  # =============================================
  # Hillside 52 Keyboard Firmware(s) - No Dongle (Left as Central)
  # =============================================
  - board: nice_nano//zmk
    shield: hillside52_left
    artifact-name: hillside52_left-central
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=y -DCONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=1 

  - board: nice_nano//zmk
    shield: hillside52_right
    artifact-name: hillside52_right-peripheral

  ## =============================================
  ## settings_reset Firmware For Each Device
  ## =============================================
  # - board: nice_nano//zmk
  #   shield: settings_reset
  # - board: xiao_ble//zmk
  #   shield: settings_reset
  ## =============================================
  ## Hillside 52 Dongle Firmware(s) - Dongle Mode (Both Halves Peripheral)
  ## =============================================
  # - board: xiao_ble//zmk
  #   shield: hillside52_dongle
  #   artifact-name: hillside52_dongle
  #   snippet: studio-rpc-usb-uart zmk-usb-logging
  #   cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=y -DCONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2 
  #
  # - board: nice_nano//zmk
  #   shield: hillside52_left
  #   artifact-name: hillside52_left-peripheral

