# **NOTE** 
#   - cmake-args are only used on Central Board
#
#   - Disable Dongle: 
#     -> Remove '-DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n' from cmake-args
#
#   - Disable Studio
#     --> Remove 'snippet: studio-rpc-usb-uart' and '-DCONFIG_ZMK_STUDIO=y' from cmake-args
---
include:

  # =============================================
  # settings_reset Firmware For Each Device
  # =============================================
  # settings_reset For Hillside 52 Keyboard
  - board: nice_nano
    shield: settings_reset
  # settings_reset For Hillside 52 Dongle
  - board: xiao_ble
    shield: settings_reset

  # =============================================
  # Hillside 52 Keyboard Firmware(s) (Peripheral) 
  # =============================================
  # Left Board
  - board: nice_nano
    shield: hillside52_left
  # Right Board
  - board: nice_nano
    shield: hillside52_right

  # =============================================
  # Hillside 52 Dongle Firmware (Central)
  # =============================================
  - board: xiao_ble
    shield: hillside52_dongle
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n -DCONFIG_ZMK_STUDIO=y

