## ========== System ==========
CONFIG_ZMK_HID_INDICATORS=y
CONFIG_ZMK_HID_SEPARATE_MOD_RELEASE_REPORT=y
CONFIG_ZMK_HID_REPORT_TYPE_NKRO=y
CONFIG_ZMK_HID_CONSUMER_REPORT_USAGES_FULL=y
CONFIG_ZMK_WPM=y

## ========== Battery Level ==========
CONFIG_ZMK_BATTERY_REPORTING=y
CONFIG_ZMK_BATTERY_REPORT_INTERVAL=450

## ========== Power Management ==========
CONFIG_ZMK_IDLE_TIMEOUT=30000
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=300000

## ========== Bluetooth ==========
CONFIG_BT_BAS=y
CONFIG_ZMK_BLE_CLEAR_BONDS_ON_START=n
CONFIG_ZMK_BLE_EXPERIMENTAL_FEATURES=n
CONFIG_ZMK_BLE_PASSKEY_ENTRY=n

## ========== OPTIONAL ==========
## ----- Keyboard Scan Optional -----
# CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=-1
# CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=-1

#################################################################################
#       ╭──────────────────────╮       #       ╭──────────────────────╮       #
# ╭─────|                      |─────╮ # ╭─────|                      |─────╮ #
# │╭─╮BAT-                     BAT+╭╮│ # │╭╮BAT+                      BAT-╭╮│ #
# │╰─╯╭╮│                      │╭╮ ╰╯│ # │╰╯ ╭╮│                      │╭╮ ╰╯│ #
# │   ╰╯│                      │╰╯   │ # │   ╰╯│                      │╰╯   │ #
# │╭─╮[1] LED                  RAW╭─╮│ # │╭─╮RAW                  LED [1]╭─╮│ #
# │╰─╯╭╮│──────────────────────│╭╮╰─╯│ # │╰─╯╭╮│──────────────────────│╭╮╰─╯│ #
# │╭─╮╰╯                        ╰╯╭─╮│ # │╭─╮╰╯                        ╰╯╭─╮│ #
# │╰─╯[0] DATA                 GND╰─╯│ # │╰─╯GND                 DATA [0]╰─╯│ #
# │╭─╮                            ╭─╮│ # │╭─╮                            ╭─╮│ #
# │╰─╯GND                      RST╰─╯│ # │╰─╯RST                     GND ╰─╯│ #
# │╭─╮                            ╭─╮│ # │╭─╮                            ╭─╮│ #
# │╰─╯GND                      VCC╰─╯│ # │╰─╯VCC                     GND ╰─╯│ #
# │╭─╮                            ╭─╮│ # │╭─╮                            ╭─╮│ #
# │╰─╯[2] SDA           [21] ENC_B╰─╯│ # │╰─╯[21] ENC_B           SDA [2]╰─╯│ #
# │╭─╮                            ╭─╮│ # │╭─╮                            ╭─╮│ #
# │╰─╯[3] SCL           [20] ENC_A╰─╯│ # │╰─╯[20] ENC_A           SCL [3]╰─╯│ #
# │╭─╮                            ╭─╮│ # │╭─╮                            ╭─╮│ #
# │╰─╯[4] C4             [19] COL0╰─╯│ # │╰─╯[19] COL0             C4 [4]╰─╯│ #
# │╭─╮                            ╭─╮│ # │╭─╮                            ╭─╮│ #
# │╰─╯[5] ROW0           COL1 [18]╰─╯│ # │╰─╯[18] COL1           ROW0 [5]╰─╯│ #
# │╭─╮                            ╭─╮│ # │╭─╮                            ╭─╮│ #
# │╰─╯[6] ROW1           COL2 [15]╰─╯│ # │╰─╯[15] COL2           ROW1 [6]╰─╯│ #
# │╭─╮                            ╭─╮│ # │╭─╮                            ╭─╮│ #
# │╰─╯[7] ROW2           COL3 [14]╰─╯│ # │╰─╯[14] COL3           ROW2 [7]╰─╯│ #
# │╭─╮                            ╭─╮│ # │╭─╮                            ╭─╮│ #
# │╰─╯[8] ROW3           COL4 [16]╰─╯│ # │╰─╯[16] COL4           ROW3 [8]╰─╯│ #
# │╭─╮                            ╭─╮│ # │╭─╮                            ╭─╮│ #
# │╰─╯[9] ROW4           COL5 [10]╰─╯│ # │╰─╯[10] COL5           ROW4 [9]╰─╯│ #
# ╰──────────────────────────────────╯ # ╰──────────────────────────────────╯ #
#################################################################################
